name: Run tests and checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Change to flask-boilerplate directory
        run: cd flask-boilerplate

      - name: Install dependencies
        working-directory: ./flask-boilerplate
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage coverage-badge

      - name: Run tests and generate coverage
        working-directory: ./flask-boilerplate
        run: |
          python -m coverage run -m unittest test_app.py
          python -m coverage report
          python -m coverage xml

      - name: Generate Coverage Badge
        run: |
          mkdir -p .github/badges
          cd flask-boilerplate
          coverage-badge -f -o ../.github/badges/coverage.svg

      - name: Log coverage percentage
        working-directory: ./flask-boilerplate
        run: |
          coverage report | grep TOTAL | awk '{print $NF}' | sed 's/%//' | xargs -I {} echo "Coverage Percentage: {}%"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add .github/badges/coverage.svg
            git commit -m "Autogenerated Python coverage badge [skip ci]"
            git pull --rebase origin main
            git push
          fi

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: python-coverage-report
          path: flask-boilerplate/coverage.xml